# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8ba86d6d3f4524fa6ac9a8f01966f71f54453914e17407cf7f07675463c91cc42f4cab5cedcf30f3369d756d0f22d9cae82fff3fe721157cfcf9f9cc7656e2f

test:
  secret_key_base: 987e051b48beec53fe36e3e55fb80b823aaa93aa66be5c19bd00c5ef5358316748f578c0791f47b1e15e9201691db0a4bc632346673c589b48e5a84f283af634

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
